# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b534bc39f41b2e53c34686129ce2c748a80112cfa8d12a425770cab369a055061fd3fcef7a4583af3d3f776ab2f06166294e60023818bef8445616b788d72b2
  staff_app_id: 6f5dadf0d92dfd388b1610c85867f13512e991df019206c0c2032708806a17b6
  staff_app_secret: a6c7bbbfb0ddfb22ea2ec0bcecd24e073b7521fd68e4a2c8d86614c255cb77dc
  staff_app_url: http://localhost:3000/
  recruitment:
    auth_token: 28d311a1e2727c6d1e6d2a04a9447407
    url: "http://localhost:3001"
    employees_api:
      by_name_path: "/v1/employees/by_name"


test:
  secret_key_base: 84ed34039a4a3330e6f3f3ee3d39b79291e8c304b5993251ed87db95dc029746cdeaf0edbe57b425fed8c60855b03654272c00fa2b5f3825b2541f5cfe401143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
